os:
  - linux
language: node_js
node_js:
  - "6.11.3"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
before_install:
  gradle wrapper
script:
  - chmod +x gradlew
  - ./gradlew clean test
  - ./gradlew bootRepackage -Pprod -x test
